
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app1:
    build: .
    container_name: app1
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  app2:
    build: .
    container_name: app2
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - app1
      - app2

  data-inserter:
    image: php:8.2-cli
    volumes:
      - ./data-inserter:/var/www/html
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy
    command: ["php", "inserter.php"]

volumes:
  db-data:
